//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWebService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.UserWebServiceSoap")]
    public interface UserWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAll", ReplyAction="*")]
        testWebService.ServiceReference1.ListAllResponse ListAll(testWebService.ServiceReference1.ListAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAll", ReplyAction="*")]
        System.Threading.Tasks.Task<testWebService.ServiceReference1.ListAllResponse> ListAllAsync(testWebService.ServiceReference1.ListAllRequest request);
        
        // CODEGEN: Generating message contract since element name ListAll1Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAll1", ReplyAction="*")]
        testWebService.ServiceReference1.ListAll1Response ListAll1(testWebService.ServiceReference1.ListAll1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAll1", ReplyAction="*")]
        System.Threading.Tasks.Task<testWebService.ServiceReference1.ListAll1Response> ListAll1Async(testWebService.ServiceReference1.ListAll1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAll", Namespace="http://tempuri.org/", Order=0)]
        public testWebService.ServiceReference1.ListAllRequestBody Body;
        
        public ListAllRequest() {
        }
        
        public ListAllRequest(testWebService.ServiceReference1.ListAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAllRequestBody {
        
        public ListAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public testWebService.ServiceReference1.ListAllResponseBody Body;
        
        public ListAllResponse() {
        }
        
        public ListAllResponse(testWebService.ServiceReference1.ListAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public testWebService.ServiceReference1.User[] ListAllResult;
        
        public ListAllResponseBody() {
        }
        
        public ListAllResponseBody(testWebService.ServiceReference1.User[] ListAllResult) {
            this.ListAllResult = ListAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAll1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAll1", Namespace="http://tempuri.org/", Order=0)]
        public testWebService.ServiceReference1.ListAll1RequestBody Body;
        
        public ListAll1Request() {
        }
        
        public ListAll1Request(testWebService.ServiceReference1.ListAll1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAll1RequestBody {
        
        public ListAll1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAll1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAll1Response", Namespace="http://tempuri.org/", Order=0)]
        public testWebService.ServiceReference1.ListAll1ResponseBody Body;
        
        public ListAll1Response() {
        }
        
        public ListAll1Response(testWebService.ServiceReference1.ListAll1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAll1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public testWebService.ServiceReference1.User[] ListAll1Result;
        
        public ListAll1ResponseBody() {
        }
        
        public ListAll1ResponseBody(testWebService.ServiceReference1.User[] ListAll1Result) {
            this.ListAll1Result = ListAll1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserWebServiceSoapChannel : testWebService.ServiceReference1.UserWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWebServiceSoapClient : System.ServiceModel.ClientBase<testWebService.ServiceReference1.UserWebServiceSoap>, testWebService.ServiceReference1.UserWebServiceSoap {
        
        public UserWebServiceSoapClient() {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testWebService.ServiceReference1.ListAllResponse testWebService.ServiceReference1.UserWebServiceSoap.ListAll(testWebService.ServiceReference1.ListAllRequest request) {
            return base.Channel.ListAll(request);
        }
        
        public testWebService.ServiceReference1.User[] ListAll() {
            testWebService.ServiceReference1.ListAllRequest inValue = new testWebService.ServiceReference1.ListAllRequest();
            inValue.Body = new testWebService.ServiceReference1.ListAllRequestBody();
            testWebService.ServiceReference1.ListAllResponse retVal = ((testWebService.ServiceReference1.UserWebServiceSoap)(this)).ListAll(inValue);
            return retVal.Body.ListAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testWebService.ServiceReference1.ListAllResponse> testWebService.ServiceReference1.UserWebServiceSoap.ListAllAsync(testWebService.ServiceReference1.ListAllRequest request) {
            return base.Channel.ListAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<testWebService.ServiceReference1.ListAllResponse> ListAllAsync() {
            testWebService.ServiceReference1.ListAllRequest inValue = new testWebService.ServiceReference1.ListAllRequest();
            inValue.Body = new testWebService.ServiceReference1.ListAllRequestBody();
            return ((testWebService.ServiceReference1.UserWebServiceSoap)(this)).ListAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testWebService.ServiceReference1.ListAll1Response testWebService.ServiceReference1.UserWebServiceSoap.ListAll1(testWebService.ServiceReference1.ListAll1Request request) {
            return base.Channel.ListAll1(request);
        }
        
        public testWebService.ServiceReference1.User[] ListAll1() {
            testWebService.ServiceReference1.ListAll1Request inValue = new testWebService.ServiceReference1.ListAll1Request();
            inValue.Body = new testWebService.ServiceReference1.ListAll1RequestBody();
            testWebService.ServiceReference1.ListAll1Response retVal = ((testWebService.ServiceReference1.UserWebServiceSoap)(this)).ListAll1(inValue);
            return retVal.Body.ListAll1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testWebService.ServiceReference1.ListAll1Response> testWebService.ServiceReference1.UserWebServiceSoap.ListAll1Async(testWebService.ServiceReference1.ListAll1Request request) {
            return base.Channel.ListAll1Async(request);
        }
        
        public System.Threading.Tasks.Task<testWebService.ServiceReference1.ListAll1Response> ListAll1Async() {
            testWebService.ServiceReference1.ListAll1Request inValue = new testWebService.ServiceReference1.ListAll1Request();
            inValue.Body = new testWebService.ServiceReference1.ListAll1RequestBody();
            return ((testWebService.ServiceReference1.UserWebServiceSoap)(this)).ListAll1Async(inValue);
        }
    }
}
